/*IMPORT INMOBILIARIAS*/

insert into inmobiliaria (Nombre, Email, Telefono) values ('Katz', 'fjarrel0@alexa.com', '(931) 6210791');
insert into inmobiliaria (Nombre, Email, Telefono) values ('Mycat', 'kpoyzer1@nasa.gov', '(937) 9183433');
insert into inmobiliaria (Nombre, Email, Telefono) values ('Trilith', 'ffiveash2@unesco.org', '(842) 9820238');
insert into inmobiliaria (Nombre, Email, Telefono) values ('Blogspan', 'adaughtery3@sun.com', '(621) 5873314');
insert into inmobiliaria (Nombre, Email, Telefono) values ('Topicware', 'dswadlen4@foxnews.com', '(654) 4376517');
insert into inmobiliaria (Nombre, Email, Telefono) values ('Browsezoom', 'dmacsherry5@sitemeter.com', '(607) 4770757');
insert into inmobiliaria (Nombre, Email, Telefono) values ('Centizu', 'lbottelstone6@cbc.ca', '(350) 6840308');
insert into inmobiliaria (Nombre, Email, Telefono) values ('Quinu', 'dolahy7@va.gov', '(449) 7125359');
insert into inmobiliaria (Nombre, Email, Telefono) values ('Pixope', 'wventam8@bing.com', '(909) 2739577');
insert into inmobiliaria (Nombre, Email, Telefono) values ('Thoughtblab', 'scodi9@bbb.org', '(448) 8840966');


/*IMPORTS PROPIETARIOS*/

insert into persona (dtype ,nombre, apellidos, email, telefono, avatar) values ('P','Gibby', 'Marcombe', 'gmarcombe0@tinypic.com', '+51 394 978 6625', 'http://google.fr/lectus.aspx?imperdiet=cursus&sapien=vestibulum&urna=proin&pretium=eu&nisl=mi&ut=nulla&volutpat=ac&sapien=enim&arcu=in&sed=tempor&augue=turpis&aliquam=nec&erat=euismod&volutpat=scelerisque&in=quam&congue=turpis&etiam=adipiscing&justo=lorem&etiam=vitae&pretium=mattis&iaculis=nibh&justo=ligula&in=nec&hac=sem&habitasse=duis&platea=aliquam&dictumst=convallis&etiam=nunc&faucibus=proin&cursus=at&urna=turpis&ut=a&tellus=pede&nulla=posuere&ut=nonummy&erat=integer&id=non&mauris=velit');
insert into persona (dtype, nombre, apellidos, email, telefono, avatar) values ('P', 'Heriberto', 'Peteri', 'hpeteri0@flavors.me', '+33 558 608 6287', 'http://vinaora.com/platea/dictumst/etiam/faucibus/cursus/urna.js?dictumst=a&morbi=pede&vestibulum=posuere&velit=nonummy&id=integer');
insert into persona (dtype, nombre, apellidos, email, telefono, avatar) values ('P', 'Kincaid', 'O''Garmen', 'kogarmen1@livejournal.com', '+48 477 659 0827', 'http://sbwire.com/enim/in/tempor/turpis.aspx?at=vel&velit=accumsan&vivamus=tellus&vel=nisi&nulla=eu&eget=orci&eros=mauris&elementum=lacinia&pellentesque=sapien&quisque=quis&porta=libero&volutpat=nullam&erat=sit&quisque=amet&erat=turpis&eros=elementum&viverra=ligula&eget=vehicula&congue=consequat&eget=morbi&semper=a&rutrum=ipsum&nulla=integer&nunc=a&purus=nibh&phasellus=in&in=quis&felis=justo&donec=maecenas&semper=rhoncus&sapien=aliquam&a=lacus&libero=morbi&nam=quis&dui=tortor&proin=id&leo=nulla&odio=ultrices&porttitor=aliquet&id=maecenas&consequat=leo&in=odio&consequat=condimentum&ut=id&nulla=luctus&sed=nec&accumsan=molestie&felis=sed&ut=justo&at=pellentesque&dolor=viverra&quis=pede&odio=ac&consequat=diam&varius=cras&integer=pellentesque&ac=volutpat&leo=dui&pellentesque=maecenas&ultrices=tristique&mattis=est&odio=et&donec=tempus&vitae=semper&nisi=est&nam=quam&ultrices=pharetra&libero=magna&non=ac&mattis=consequat&pulvinar=metus&nulla=sapien&pede=ut&ullamcorper=nunc&augue=vestibulum&a=ante&suscipit=ipsum&nulla=primis&elit=in&ac=faucibus&nulla=orci&sed=luctus&vel=et&enim=ultrices&sit=posuere&amet=cubilia&nunc=curae&viverra=mauris&dapibus=viverra&nulla=diam&suscipit=vitae&ligula=quam&in=suspendisse&lacus=potenti&curabitur=nullam&at=porttitor&ipsum=lacus&ac=at');
insert into persona (dtype, nombre, apellidos, email, telefono, avatar) values ('P', 'Phillis', 'Lilleycrop', 'plilleycrop2@ebay.co.uk', '+86 906 696 5647', 'http://cyberchimps.com/sit/amet/sapien.json?mi=vestibulum&sit=quam&amet=sapien&lobortis=varius&sapien=ut&sapien=blandit&non=non&mi=interdum&integer=in&ac=ante&neque=vestibulum&duis=ante&bibendum=ipsum&morbi=primis&non=in&quam=faucibus&nec=orci&dui=luctus&luctus=et&rutrum=ultrices&nulla=posuere&tellus=cubilia&in=curae&sagittis=duis&dui=faucibus&vel=accumsan&nisl=odio&duis=curabitur&ac=convallis&nibh=duis&fusce=consequat&lacus=dui&purus=nec&aliquet=nisi&at=volutpat&feugiat=eleifend&non=donec&pretium=ut&quis=dolor&lectus=morbi&suspendisse=vel&potenti=lectus&in=in&eleifend=quam&quam=fringilla&a=rhoncus&odio=mauris&in=enim&hac=leo&habitasse=rhoncus&platea=sed&dictumst=vestibulum&maecenas=sit&ut=amet&massa=cursus&quis=id&augue=turpis&luctus=integer&tincidunt=aliquet&nulla=massa&mollis=id&molestie=lobortis&lorem=convallis&quisque=tortor&ut=risus&erat=dapibus&curabitur=augue&gravida=vel&nisi=accumsan&at=tellus&nibh=nisi&in=eu&hac=orci&habitasse=mauris&platea=lacinia&dictumst=sapien');
insert into persona (dtype, nombre, apellidos, email, telefono, avatar) values ('P', 'Justinn', 'Usborn', 'jusborn3@freewebs.com', '+374 232 853 9076', 'http://buzzfeed.com/quis/libero/nullam/sit/amet/turpis.xml?feugiat=proin&et=interdum&eros=mauris&vestibulum=non&ac=ligula&est=pellentesque&lacinia=ultrices&nisi=phasellus&venenatis=id&tristique=sapien&fusce=in&congue=sapien&diam=iaculis&id=congue');
insert into persona (dtype, nombre, apellidos, email, telefono, avatar) values ('P', 'Caty', 'Blanche', 'cblanche4@instagram.com', '+63 197 929 2552', 'https://arizona.edu/pellentesque/eget.js?ligula=orci&nec=luctus&sem=et&duis=ultrices&aliquam=posuere&convallis=cubilia&nunc=curae&proin=mauris&at=viverra&turpis=diam&a=vitae&pede=quam&posuere=suspendisse&nonummy=potenti&integer=nullam&non=porttitor&velit=lacus&donec=at&diam=turpis&neque=donec&vestibulum=posuere&eget=metus&vulputate=vitae&ut=ipsum&ultrices=aliquam&vel=non&augue=mauris&vestibulum=morbi&ante=non&ipsum=lectus&primis=aliquam&in=sit&faucibus=amet&orci=diam&luctus=in&et=magna&ultrices=bibendum&posuere=imperdiet&cubilia=nullam&curae=orci&donec=pede&pharetra=venenatis&magna=non&vestibulum=sodales&aliquet=sed&ultrices=tincidunt&erat=eu&tortor=felis&sollicitudin=fusce&mi=posuere&sit=felis&amet=sed&lobortis=lacus&sapien=morbi&sapien=sem&non=mauris&mi=laoreet&integer=ut&ac=rhoncus&neque=aliquet&duis=pulvinar&bibendum=sed&morbi=nisl&non=nunc&quam=rhoncus&nec=dui&dui=vel&luctus=sem&rutrum=sed&nulla=sagittis&tellus=nam&in=congue&sagittis=risus&dui=semper&vel=porta&nisl=volutpat&duis=quam&ac=pede&nibh=lobortis&fusce=ligula&lacus=sit&purus=amet&aliquet=eleifend&at=pede&feugiat=libero&non=quis&pretium=orci&quis=nullam&lectus=molestie&suspendisse=nibh&potenti=in&in=lectus&eleifend=pellentesque&quam=at&a=nulla&odio=suspendisse&in=potenti&hac=cras&habitasse=in&platea=purus');
insert into persona (dtype, nombre, apellidos, email, telefono, avatar) values ('P', 'Piotr', 'Zorzin', 'pzorzin5@weather.com', '+84 518 320 6356', 'http://businessinsider.com/adipiscing/molestie/hendrerit.jpg?dui=ligula&luctus=nec&rutrum=sem&nulla=duis&tellus=aliquam&in=convallis&sagittis=nunc&dui=proin&vel=at&nisl=turpis&duis=a&ac=pede&nibh=posuere&fusce=nonummy&lacus=integer&purus=non&aliquet=velit&at=donec&feugiat=diam&non=neque&pretium=vestibulum&quis=eget&lectus=vulputate&suspendisse=ut&potenti=ultrices&in=vel&eleifend=augue&quam=vestibulum&a=ante&odio=ipsum&in=primis&hac=in&habitasse=faucibus&platea=orci&dictumst=luctus&maecenas=et&ut=ultrices&massa=posuere&quis=cubilia&augue=curae&luctus=donec&tincidunt=pharetra&nulla=magna&mollis=vestibulum&molestie=aliquet&lorem=ultrices&quisque=erat&ut=tortor&erat=sollicitudin&curabitur=mi&gravida=sit&nisi=amet&at=lobortis&nibh=sapien&in=sapien&hac=non&habitasse=mi&platea=integer&dictumst=ac&aliquam=neque&augue=duis&quam=bibendum&sollicitudin=morbi&vitae=non&consectetuer=quam&eget=nec&rutrum=dui&at=luctus&lorem=rutrum&integer=nulla&tincidunt=tellus&ante=in&vel=sagittis&ipsum=dui&praesent=vel&blandit=nisl&lacinia=duis&erat=ac&vestibulum=nibh&sed=fusce');
insert into persona (dtype, nombre, apellidos, email, telefono, avatar) values ('P', 'Sioux', 'Hulatt', 'shulatt6@etsy.com', '+63 208 514 9193', 'https://diigo.com/vel/sem.jpg?sociis=lorem&natoque=id&penatibus=ligula&et=suspendisse&magnis=ornare&dis=consequat&parturient=lectus&montes=in&nascetur=est&ridiculus=risus&mus=auctor&etiam=sed&vel=tristique&augue=in');
insert into persona (dtype, nombre, apellidos, email, telefono, avatar) values ('P', 'Garrick', 'Grenter', 'ggrenter7@storify.com', '+86 991 146 6735', 'https://ameblo.jp/nunc/proin.jpg?morbi=sollicitudin&non=ut&lectus=suscipit&aliquam=a&sit=feugiat&amet=et&diam=eros&in=vestibulum&magna=ac&bibendum=est&imperdiet=lacinia&nullam=nisi&orci=venenatis&pede=tristique&venenatis=fusce&non=congue&sodales=diam&sed=id&tincidunt=ornare&eu=imperdiet&felis=sapien&fusce=urna&posuere=pretium&felis=nisl&sed=ut&lacus=volutpat&morbi=sapien&sem=arcu&mauris=sed&laoreet=augue&ut=aliquam&rhoncus=erat&aliquet=volutpat&pulvinar=in&sed=congue&nisl=etiam&nunc=justo&rhoncus=etiam&dui=pretium&vel=iaculis&sem=justo&sed=in&sagittis=hac&nam=habitasse&congue=platea&risus=dictumst&semper=etiam&porta=faucibus&volutpat=cursus');
insert into persona (dtype, nombre, apellidos, email, telefono, avatar) values ('P', 'Christa', 'Deniset', 'cdeniset8@reference.com', '+46 771 522 8550', 'https://uiuc.edu/a/odio/in/hac/habitasse/platea.xml?quisque=elit&ut=sodales&erat=scelerisque&curabitur=mauris&gravida=sit&nisi=amet&at=eros&nibh=suspendisse&in=accumsan&hac=tortor&habitasse=quis&platea=turpis&dictumst=sed&aliquam=ante&augue=vivamus&quam=tortor&sollicitudin=duis&vitae=mattis&consectetuer=egestas&eget=metus&rutrum=aenean&at=fermentum&lorem=donec&integer=ut&tincidunt=mauris&ante=eget&vel=massa&ipsum=tempor&praesent=convallis&blandit=nulla&lacinia=neque&erat=libero&vestibulum=convallis&sed=eget&magna=eleifend&at=luctus&nunc=ultricies&commodo=eu&placerat=nibh&praesent=quisque&blandit=id&nam=justo&nulla=sit&integer=amet&pede=sapien&justo=dignissim&lacinia=vestibulum&eget=vestibulum&tincidunt=ante&eget=ipsum&tempus=primis&vel=in&pede=faucibus&morbi=orci&porttitor=luctus&lorem=et&id=ultrices&ligula=posuere&suspendisse=cubilia&ornare=curae&consequat=nulla&lectus=dapibus&in=dolor&est=vel&risus=est&auctor=donec&sed=odio&tristique=justo&in=sollicitudin&tempus=ut&sit=suscipit&amet=a&sem=feugiat&fusce=et&consequat=eros&nulla=vestibulum&nisl=ac&nunc=est&nisl=lacinia&duis=nisi&bibendum=venenatis&felis=tristique&sed=fusce&interdum=congue&venenatis=diam&turpis=id');
insert into persona (dtype, nombre, apellidos, email, telefono, avatar) values ('P', 'Lara', 'Orgen', 'lorgen9@wordpress.com', '+63 360 624 7764', 'http://dell.com/sit/amet/eleifend.jpg?fermentum=amet&donec=nunc&ut=viverra&mauris=dapibus&eget=nulla&massa=suscipit&tempor=ligula&convallis=in&nulla=lacus&neque=curabitur&libero=at&convallis=ipsum&eget=ac&eleifend=tellus&luctus=semper&ultricies=interdum&eu=mauris&nibh=ullamcorper&quisque=purus&id=sit&justo=amet&sit=nulla&amet=quisque&sapien=arcu&dignissim=libero&vestibulum=rutrum&vestibulum=ac&ante=lobortis&ipsum=vel&primis=dapibus&in=at&faucibus=diam&orci=nam');
insert into persona (dtype, nombre, apellidos, email, telefono, avatar) values ('P', 'Wallie', 'Coper', 'wcopera@netlog.com', '+63 869 899 0429', 'http://netlog.com/nunc/rhoncus/dui/vel.aspx?nunc=nunc&nisl=donec&duis=quis&bibendum=orci&felis=eget&sed=orci&interdum=vehicula&venenatis=condimentum&turpis=curabitur&enim=in&blandit=libero&mi=ut&in=massa&porttitor=volutpat&pede=convallis&justo=morbi&eu=odio&massa=odio&donec=elementum&dapibus=eu&duis=interdum&at=eu&velit=tincidunt&eu=in&est=leo&congue=maecenas&elementum=pulvinar&in=lobortis&hac=est&habitasse=phasellus&platea=sit&dictumst=amet&morbi=erat&vestibulum=nulla&velit=tempus&id=vivamus&pretium=in&iaculis=felis&diam=eu');
insert into persona (dtype, nombre, apellidos, email, telefono, avatar) values ('P', 'Carola', 'Mytton', 'cmyttonb@unesco.org', '+383 395 175 4193', 'https://utexas.edu/pede/ullamcorper/augue/a/suscipit.aspx?ultrices=pede&enim=justo&lorem=eu&ipsum=massa&dolor=donec&sit=dapibus&amet=duis&consectetuer=at&adipiscing=velit&elit=eu&proin=est&interdum=congue&mauris=elementum&non=in&ligula=hac&pellentesque=habitasse&ultrices=platea&phasellus=dictumst&id=morbi&sapien=vestibulum&in=velit&sapien=id&iaculis=pretium&congue=iaculis&vivamus=diam&metus=erat&arcu=fermentum&adipiscing=justo&molestie=nec&hendrerit=condimentum&at=neque&vulputate=sapien&vitae=placerat&nisl=ante&aenean=nulla&lectus=justo&pellentesque=aliquam&eget=quis&nunc=turpis&donec=eget&quis=elit&orci=sodales&eget=scelerisque&orci=mauris&vehicula=sit&condimentum=amet&curabitur=eros&in=suspendisse&libero=accumsan&ut=tortor&massa=quis&volutpat=turpis&convallis=sed&morbi=ante&odio=vivamus&odio=tortor');
insert into persona (dtype, nombre, apellidos, email, telefono, avatar) values ('P', 'Beckie', 'Hinrichs', 'bhinrichsc@zimbio.com', '+46 970 324 3698', 'https://fda.gov/justo/nec.jpg?eu=ac&est=diam&congue=cras&elementum=pellentesque&in=volutpat&hac=dui&habitasse=maecenas&platea=tristique&dictumst=est&morbi=et&vestibulum=tempus&velit=semper&id=est&pretium=quam&iaculis=pharetra&diam=magna&erat=ac&fermentum=consequat&justo=metus&nec=sapien&condimentum=ut&neque=nunc&sapien=vestibulum&placerat=ante&ante=ipsum&nulla=primis&justo=in&aliquam=faucibus&quis=orci&turpis=luctus&eget=et&elit=ultrices&sodales=posuere&scelerisque=cubilia&mauris=curae&sit=mauris&amet=viverra&eros=diam&suspendisse=vitae&accumsan=quam&tortor=suspendisse&quis=potenti&turpis=nullam&sed=porttitor&ante=lacus&vivamus=at&tortor=turpis&duis=donec&mattis=posuere&egestas=metus&metus=vitae&aenean=ipsum&fermentum=aliquam&donec=non&ut=mauris&mauris=morbi&eget=non&massa=lectus&tempor=aliquam&convallis=sit&nulla=amet&neque=diam');
insert into persona (dtype, nombre, apellidos, email, telefono, avatar) values ('P', 'Langston', 'Blamphin', 'lblamphind@blogspot.com', '+86 903 623 3085', 'http://squidoo.com/congue/etiam.aspx?aliquam=dui&quis=vel&turpis=nisl&eget=duis&elit=ac&sodales=nibh&scelerisque=fusce&mauris=lacus&sit=purus&amet=aliquet&eros=at&suspendisse=feugiat&accumsan=non');
insert into persona (dtype, nombre, apellidos, email, telefono, avatar) values ('P', 'Paxon', 'Loomes', 'ploomese@nba.com', '+58 569 700 0105', 'http://smugmug.com/erat/curabitur/gravida/nisi/at.jsp?rutrum=ac&at=neque&lorem=duis&integer=bibendum&tincidunt=morbi&ante=non&vel=quam&ipsum=nec');
insert into persona (dtype, nombre, apellidos, email, telefono, avatar) values ('P', 'Hewie', 'Brogiotti', 'hbrogiottif@canalblog.com', '+94 949 576 4047', 'https://cmu.edu/fusce/posuere.xml?volutpat=magna&quam=ac&pede=consequat&lobortis=metus&ligula=sapien&sit=ut&amet=nunc&eleifend=vestibulum&pede=ante&libero=ipsum&quis=primis&orci=in&nullam=faucibus&molestie=orci&nibh=luctus&in=et&lectus=ultrices&pellentesque=posuere&at=cubilia&nulla=curae&suspendisse=mauris&potenti=viverra&cras=diam&in=vitae&purus=quam&eu=suspendisse&magna=potenti&vulputate=nullam&luctus=porttitor&cum=lacus&sociis=at&natoque=turpis&penatibus=donec&et=posuere&magnis=metus&dis=vitae&parturient=ipsum&montes=aliquam&nascetur=non&ridiculus=mauris&mus=morbi&vivamus=non&vestibulum=lectus&sagittis=aliquam&sapien=sit&cum=amet&sociis=diam&natoque=in&penatibus=magna&et=bibendum&magnis=imperdiet&dis=nullam&parturient=orci&montes=pede&nascetur=venenatis&ridiculus=non&mus=sodales&etiam=sed&vel=tincidunt&augue=eu&vestibulum=felis&rutrum=fusce&rutrum=posuere&neque=felis&aenean=sed&auctor=lacus&gravida=morbi&sem=sem&praesent=mauris&id=laoreet&massa=ut&id=rhoncus&nisl=aliquet&venenatis=pulvinar&lacinia=sed&aenean=nisl&sit=nunc&amet=rhoncus&justo=dui&morbi=vel&ut=sem&odio=sed&cras=sagittis');
insert into persona (dtype, nombre, apellidos, email, telefono, avatar) values ('P', 'Celinda', 'Pummery', 'cpummeryg@liveinternet.ru', '+351 566 380 1039', 'http://earthlink.net/nonummy/maecenas/tincidunt/lacus/at.xml?amet=quisque');
insert into persona (dtype, nombre, apellidos, email, telefono, avatar) values ('P', 'Livy', 'Dailly', 'ldaillyh@reverbnation.com', '+86 558 227 7211', 'http://irs.gov/sit/amet/eros/suspendisse/accumsan/tortor/quis.html?quisque=urna&ut=pretium&erat=nisl&curabitur=ut&gravida=volutpat&nisi=sapien&at=arcu&nibh=sed&in=augue&hac=aliquam&habitasse=erat&platea=volutpat&dictumst=in&aliquam=congue&augue=etiam&quam=justo&sollicitudin=etiam&vitae=pretium&consectetuer=iaculis&eget=justo&rutrum=in&at=hac&lorem=habitasse&integer=platea&tincidunt=dictumst&ante=etiam&vel=faucibus&ipsum=cursus&praesent=urna&blandit=ut&lacinia=tellus&erat=nulla&vestibulum=ut&sed=erat&magna=id&at=mauris&nunc=vulputate&commodo=elementum&placerat=nullam&praesent=varius&blandit=nulla&nam=facilisi&nulla=cras&integer=non&pede=velit&justo=nec');
insert into persona (dtype, nombre, apellidos, email, telefono, avatar) values ('P', 'Alfie', 'Albury', 'aalburyi@newyorker.com', '+380 523 500 1183', 'http://accuweather.com/consequat/ut/nulla/sed/accumsan/felis/ut.js?massa=nisl&id=duis&nisl=bibendum&venenatis=felis&lacinia=sed&aenean=interdum&sit=venenatis&amet=turpis&justo=enim&morbi=blandit&ut=mi&odio=in&cras=porttitor&mi=pede&pede=justo');
insert into persona (dtype, nombre, apellidos, email, telefono, avatar) values ('P', 'Pooh', 'Whetnall', 'pwhetnallj@shinystat.com', '+86 149 144 7780', 'http://sitemeter.com/venenatis/tristique/fusce/congue/diam/id/ornare.jsp?cubilia=dictumst&curae=maecenas&mauris=ut&viverra=massa&diam=quis&vitae=augue&quam=luctus&suspendisse=tincidunt&potenti=nulla&nullam=mollis&porttitor=molestie&lacus=lorem&at=quisque&turpis=ut&donec=erat&posuere=curabitur&metus=gravida&vitae=nisi&ipsum=at&aliquam=nibh&non=in&mauris=hac&morbi=habitasse&non=platea&lectus=dictumst&aliquam=aliquam&sit=augue&amet=quam');

/*IMPORTS VIVIENDAS*/

insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, inmobiliaria_id) values ('Kids, The (Mistons, Les) (Mischief Makers, The)', 'nec fringilla tortor rutrum a. Proin imperdiet vitae mauris id molestie. Cras placerat nulla sed porta maximus. Nam fringilla porta massa', 'https://robohash.org/estetnostrum.png?size=50x50&set=set1', 28.0846121, '1523 Cody Park', '35015', 'Canarias', 'Cataluna', 'Alquiler', '5842,37', 2, 63, 3, true, true, true, 1);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, inmobiliaria_id) values ('Lovely Molly', 'vel luctus justo pretium ut. Phasellus convallis', 'https://robohash.org/utaddolor.png?size=50x50&set=set1', 37.439299, '163 Northfield Avenue', '41015', 'Andalucia', 'Extremadura', 'Alquiler', '58212,54', 4, 53, 1, true, true, true, 1);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, inmobiliaria_id) values ('Cutthroat Island', 'quis feugiat ex malesuada at. Aliquam vitae augue neque. Phasellus sed volutpat elit.', 'https://robohash.org/autmolestiaedelectus.png?size=50x50&set=set1', 43.4717283, '8 Dawn Terrace', '39005', 'Cantabria', 'Andalucia', 'Venta', '116595,59', 4, 141, 2, true, false, false, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, inmobiliaria_id) values ('Fun with Dick and Jane', 'vel luctus justo pretium ut. Phasellus convallis', 'https://robohash.org/iustoomniscumque.png?size=50x50&set=set1', 41.3730301, '2 Hudson Street', '08904', 'Cataluna', 'Murcia', 'Alquiler', '103045,51', 5, 148, 1, false, false, true, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, inmobiliaria_id) values ('Dog Soldiers', 'Lorem ipsum dolor sit amet', 'https://robohash.org/corporisdolorumsoluta.png?size=50x50&set=set1', 37.7801069, '368 Anderson Center', '23005', 'Andalucia', 'Murcia', 'Alquiler', '62797,78', 0, 140, 3, true, true, false, 3);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, inmobiliaria_id) values ('Lords of Salem, The', 'est lectus pulvinar magna', 'https://robohash.org/teneturexercitationemrepellendus.png?size=50x50&set=set1', 28.00872, '632 Rieder Street', '35213', 'Canarias', 'Pais Vasco', 'Venta', '33406,92', 3, 40, 1, false, true, true, 3);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Kids, The (Mistons, Les) (Mischief Makers, The)', 'nec fringilla tortor rutrum a. Proin imperdiet vitae mauris id molestie. Cras placerat nulla sed porta maximus. Nam fringilla porta massa', 'https://robohash.org/estetnostrum.png?size=50x50&set=set1', 28.0846121, '1523 Cody Park', '35015', 'Canarias', 'Cataluna', 'Alquiler', 5842.37, 2, 63, 3, true, true, true, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Lovely Molly', 'vel luctus justo pretium ut. Phasellus convallis', 'https://robohash.org/utaddolor.png?size=50x50&set=set1', 37.439299, '163 Northfield Avenue', '41015', 'Andalucia', 'Extremadura', 'Alquiler', 58212.54, 4, 53, 1, true, true, true, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Cutthroat Island', 'quis feugiat ex malesuada at. Aliquam vitae augue neque. Phasellus sed volutpat elit.', 'https://robohash.org/autmolestiaedelectus.png?size=50x50&set=set1', 43.4717283, '8 Dawn Terrace', '39005', 'Cantabria', 'Andalucia', 'Venta', 116595.59, 4, 141, 2, true, false, false, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Fun with Dick and Jane', 'vel luctus justo pretium ut. Phasellus convallis', 'https://robohash.org/iustoomniscumque.png?size=50x50&set=set1', 41.3730301, '2 Hudson Street', '08904', 'Cataluna', 'Murcia', 'Alquiler', 103045.51, 5, 148, 1, false, false, true, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Dog Soldiers', 'Lorem ipsum dolor sit amet', 'https://robohash.org/corporisdolorumsoluta.png?size=50x50&set=set1', 37.7801069, '368 Anderson Center', '23005', 'Andalucia', 'Murcia', 'Alquiler', 62797.78, 0, 140, 3, true, true, false, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Lords of Salem, The', 'est lectus pulvinar magna', 'https://robohash.org/teneturexercitationemrepellendus.png?size=50x50&set=set1', 28.00872, '632 Rieder Street', '35213', 'Canarias', 'Pais Vasco', 'Venta', 33406.92, 3, 40, 1, false, true, true, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Caesar Must Die (Cesare deve morire)', 'consectetur neque. Morbi tempor odio non sodales elementum. Duis mattis vestibulum dapibus. Etiam consequat eros sed nisi pellentesque bibendum. Curabitur eleifend malesuada ligula', 'https://robohash.org/cumqueenimvoluptate.png?size=50x50&set=set1', 41.4904044, '823 Washington Center', '08190', 'Cataluna', 'Castilla - Leon', 'Venta', 24545.30, 5, 115, 2, true, true, true, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Michael', 'est lectus pulvinar magna', 'https://robohash.org/laudantiumautpariatur.png?size=50x50&set=set1', 42.8518656, '15162 Gerald Drive', '15899', 'Galicia', 'Galicia', 'Venta', 19056.93, 1, 95, 3, false, true, false, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Bratz: The Movie', 'Lorem ipsum dolor sit amet', 'https://robohash.org/eaqueveritatisreprehenderit.png?size=50x50&set=set1', 40.9380536, '621 Tomscot Park', '43071', 'Cataluna', 'Pais Vasco', 'Alquiler', 92479.67, 5, 68, 1, false, true, true, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Actress, the Dollars and the Transylvanians, The (Artista, dolarii si Ardelenii)', 'nec fringilla tortor rutrum a. Proin imperdiet vitae mauris id molestie. Cras placerat nulla sed porta maximus. Nam fringilla porta massa', 'https://robohash.org/errorquisalias.png?size=50x50&set=set1', 37.1952335, '2117 Magdeline Junction', '18015', 'Andalucia', 'Galicia', 'Venta', 64627.25, 4, 75, 1, false, false, false, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Berlin Alexanderplatz', 'consectetur neque. Morbi tempor odio non sodales elementum. Duis mattis vestibulum dapibus. Etiam consequat eros sed nisi pellentesque bibendum. Curabitur eleifend malesuada ligula', 'https://robohash.org/harumsintquod.png?size=50x50&set=set1', 40.9380536, '80 Thierer Hill', '43071', 'Cataluna', 'Cataluna', 'Obra nueva', 107450.77, 1, 79, 3, true, true, true, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('John Doe: Vigilante', 'vitae commodo ipsum ligula vitae neque. Pellentesque in enim at risus malesuada faucibus non a augue. Cras porta ultrices ligula', 'https://robohash.org/namaspernaturqui.png?size=50x50&set=set1', 37.4212157, '20759 Scoville Lane', '41020', 'Andalucia', 'Castilla - Leon', 'Venta', 86934.36, 3, 87, 0, true, true, false, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Girl on the Train, The (La fille du RER)', 'consectetur neque. Morbi tempor odio non sodales elementum. Duis mattis vestibulum dapibus. Etiam consequat eros sed nisi pellentesque bibendum. Curabitur eleifend malesuada ligula', 'https://robohash.org/totamculpaveritatis.png?size=50x50&set=set1', 41.6247751, '91 Kenwood Center', '25193', 'Cataluna', 'Galicia', 'Venta', 46963.80, 1, 142, 1, true, false, true, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Cherry Crush', 'porttitor metus in', 'https://robohash.org/voluptasculpavoluptatem.png?size=50x50&set=set1', 36.7195014, '2 Monica Street', '29005', 'Andalucia', 'Murcia', 'Venta', 100433.29, 2, 49, 3, false, false, false, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Foul Play', 'consectetur neque. Morbi tempor odio non sodales elementum. Duis mattis vestibulum dapibus. Etiam consequat eros sed nisi pellentesque bibendum. Curabitur eleifend malesuada ligula', 'https://robohash.org/adrepellatconsectetur.png?size=50x50&set=set1', 41.4904044, '90023 Oak Trail', '08190', 'Cataluna', 'Castilla - La Mancha', 'Obra nueva', 19290.68, 1, 123, 3, false, true, true, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Vivre sa vie: Film en douze tableaux (My Life to Live)', 'porttitor metus in', 'https://robohash.org/repudiandaeestcum.png?size=50x50&set=set1', 41.4378689, '01 Longview Street', '08030', 'Cataluna', 'Comunidad Valenciana', 'Alquiler', 82230.56, 0, 107, 3, false, false, true, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Billy the Kid vs. Dracula', 'nec fringilla tortor rutrum a. Proin imperdiet vitae mauris id molestie. Cras placerat nulla sed porta maximus. Nam fringilla porta massa', 'https://robohash.org/aliasexpeditaquo.png?size=50x50&set=set1', 37.5968793, '5723 Graedel Hill', '30394', 'Murcia', 'Extremadura', 'Alquiler', 114307.79, 1, 102, 0, true, false, false, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Little Giant, The', 'est lectus pulvinar magna', 'https://robohash.org/nemomolestiaeut.png?size=50x50&set=set1', 42.4556093, '84663 Basil Street', '36156', 'Galicia', 'Comunidad Valenciana', 'Venta', 37748.12, 0, 128, 2, false, true, true, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Joshua', 'dolor nec auctor finibus', 'https://robohash.org/dolorumetquisquam.png?size=50x50&set=set1', 42.5944931, '34 Linden Road', '24010', 'Castilla - Leon', 'Castilla - La Mancha', 'Alquiler', 94004.52, 4, 67, 3, true, false, false, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('NeverEnding Story II: The Next Chapter, The', 'consectetur adipiscing elit. Etiam faucibus convallis rhoncus. Integer eget elit lacinia', 'https://robohash.org/temporibuseahic.png?size=50x50&set=set1', 37.1773363, '72995 Grasskamp Park', '18010', 'Andalucia', 'Cataluna', 'Venta', 35373.41, 1, 137, 0, false, true, true, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Rounders', 'dolor nec auctor finibus', 'https://robohash.org/etaliquidmagni.png?size=50x50&set=set1', 42.4914204, '104 Derek Park', '26005', 'La Rioja', 'Andalucia', 'Obra nueva', 39491.88, 5, 142, 3, true, true, false, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Asylum', 'consectetur adipiscing elit. Etiam faucibus convallis rhoncus. Integer eget elit lacinia', 'https://robohash.org/doloreoptioquo.png?size=50x50&set=set1', 41.4904044, '48096 Russell Parkway', '08190', 'Cataluna', 'La Rioja', 'Venta', 61799.69, 1, 55, 0, false, true, true, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Aaltra', 'vel luctus justo pretium ut. Phasellus convallis', 'https://robohash.org/laudantiumcumquesit.png?size=50x50&set=set1', 43.3177929, '6 Clemons Terrace', '20005', 'Pais Vasco', 'Galicia', 'Venta', 41323.48, 2, 52, 1, false, true, true, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Fitzgerald Family Christmas, The', 'dolor nec auctor finibus', 'https://robohash.org/debitisdolorvoluptatum.png?size=50x50&set=set1', 40.9380536, '513 Eastlawn Circle', '43071', 'Cataluna', 'Castilla - Leon', 'Venta', 104694.95, 0, 136, 1, true, true, true, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Scenesters, The', 'quis feugiat ex malesuada at. Aliquam vitae augue neque. Phasellus sed volutpat elit.', 'https://robohash.org/maximemodised.png?size=50x50&set=set1', 39.4798873, '4407 Ridge Oak Alley', '46015', 'Comunidad Valenciana', 'Castilla - Leon', 'Alquiler', 5806.54, 4, 149, 3, true, true, true, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Good Work (Beau travail)', 'Lorem ipsum dolor sit amet', 'https://robohash.org/suntsuntvero.png?size=50x50&set=set1', 38.0294026, '19165 Brickson Park Terrace', '03184', 'Comunidad Valenciana', 'Cataluna', 'Venta', 32961.88, 4, 49, 2, true, true, false, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Ear, The (Ucho)', 'dolor nec auctor finibus', 'https://robohash.org/idsolutalabore.png?size=50x50&set=set1', 42.4576548, '22784 Mesta Parkway', '26070', 'La Rioja', 'Comunidad Valenciana', 'Venta', 67349.93, 5, 106, 3, true, false, true, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Terminator, The', 'consectetur neque. Morbi tempor odio non sodales elementum. Duis mattis vestibulum dapibus. Etiam consequat eros sed nisi pellentesque bibendum. Curabitur eleifend malesuada ligula', 'https://robohash.org/quiutfacere.png?size=50x50&set=set1', 39.9863563, '68382 Maple Wood Terrace', '12100', 'Comunidad Valenciana', 'Castilla - Leon', 'Alquiler', 52002.44, 2, 76, 0, false, true, false, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Heroes of Telemark, The ', 'vel luctus justo pretium ut. Phasellus convallis', 'https://robohash.org/quodoloreratione.png?size=50x50&set=set1', 43.3177929, '0 Arapahoe Drive', '20005', 'Pais Vasco', 'Comunidad Valenciana', 'Alquiler', 10571.39, 3, 81, 3, false, false, false, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Talking About Sex', 'dolor nec auctor finibus', 'https://robohash.org/iustodoloremvoluptatum.png?size=50x50&set=set1', 41.5281384, '44138 Graceland Alley', '08204', 'Cataluna', 'Galicia', 'Obra nueva', 83322.24, 3, 35, 3, true, true, true, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Item, The', 'porttitor metus in', 'https://robohash.org/culpaaliquiditaque.png?size=50x50&set=set1', 38.8794495, '2266 Armistice Junction', '06010', 'Extremadura', 'Castilla - Leon', 'Obra nueva', 106616.17, 0, 30, 1, true, true, true, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Bird People in China, The (Chûgoku no chôjin)', 'consectetur neque. Morbi tempor odio non sodales elementum. Duis mattis vestibulum dapibus. Etiam consequat eros sed nisi pellentesque bibendum. Curabitur eleifend malesuada ligula', 'https://robohash.org/excepturisuntlabore.png?size=50x50&set=set1', 43.4880374, '2 Corben Trail', '15490', 'Galicia', 'Canarias', 'Obra nueva', 40296.8, 2, 104, 3, true, true, false, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Homer & Eddie', 'nec fringilla tortor rutrum a. Proin imperdiet vitae mauris id molestie. Cras placerat nulla sed porta maximus. Nam fringilla porta massa', 'https://robohash.org/hicquamfuga.png?size=50x50&set=set1', 39.9658255, '47 Spaight Junction', '12005', 'Comunidad Valenciana', 'Comunidad Valenciana', 'Obra nueva', 97846.01, 1, 71, 1, true, true, false, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Life Before Her Eyes, The', 'nec fringilla tortor rutrum a. Proin imperdiet vitae mauris id molestie. Cras placerat nulla sed porta maximus. Nam fringilla porta massa', 'https://robohash.org/architectoaperiamanimi.png?size=50x50&set=set1', 36.7195014, '77294 Charing Cross Street', '29005', 'Andalucia', 'Comunidad Valenciana', 'Obra nueva', 43538.74, 0, 101, 1, false, true, false, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Impulse', 'quis feugiat ex malesuada at. Aliquam vitae augue neque. Phasellus sed volutpat elit.', 'https://robohash.org/quibusdamquiaut.png?size=50x50&set=set1', 37.1952335, '3995 Rusk Pass', '18015', 'Andalucia', 'Canarias', 'Venta', 109670.98, 3, 101, 2, false, false, true, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('How to Train Your Dragon', 'est lectus pulvinar magna', 'https://robohash.org/quamsintratione.png?size=50x50&set=set1', 38.994349, '881 School Point', '02005', 'Castilla - La Mancha', 'Navarra', 'Obra nueva', 78521.66, 5, 68, 3, true, true, false, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Dead Calling, A', 'dolor nec auctor finibus', 'https://robohash.org/vitaeetqui.png?size=50x50&set=set1', 42.2390986, '8 Stephen Lane', '36215', 'Galicia', 'Andalucia', 'Alquiler', 61105.82, 3, 93, 3, true, true, true, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('After the Rehearsal (Efter repetitionen)', 'vel luctus justo pretium ut. Phasellus convallis', 'https://robohash.org/commodidelenitiqui.png?size=50x50&set=set1', 40.9838888, '96451 Orin Trail', '37005', 'Castilla - Leon', 'Cataluna', 'Obra nueva', 94319.45, 2, 133, 3, true, false, false, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Three Days of the Condor (3 Days of the Condor)', 'nec fringilla tortor rutrum a. Proin imperdiet vitae mauris id molestie. Cras placerat nulla sed porta maximus. Nam fringilla porta massa', 'https://robohash.org/rerumautomnis.png?size=50x50&set=set1', 36.757714, '5 Starling Plaza', '29071', 'Andalucia', 'Pais Vasco', 'Venta', 6960.07, 3, 106, 1, false, true, false, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Freakonomics', 'quis feugiat ex malesuada at. Aliquam vitae augue neque. Phasellus sed volutpat elit.', 'https://robohash.org/nihilnonvitae.png?size=50x50&set=set1', 42.8970535, '689 Pennsylvania Terrace', '15705', 'Galicia', 'La Rioja', 'Alquiler', 113903.04, 3, 117, 2, false, true, false, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Unfinished Piece for a Player Piano, An (Neokonchennaya pyesa dlya mekhanicheskogo pianino)', 'dolor nec auctor finibus', 'https://robohash.org/architectoexplicabovoluptatem.png?size=50x50&set=set1', 43.3152889, '0 Londonderry Terrace', '20015', 'Pais Vasco', 'Cataluna', 'Obra nueva', 99596.51, 1, 57, 3, false, false, true, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Miracles', 'vitae commodo ipsum ligula vitae neque. Pellentesque in enim at risus malesuada faucibus non a augue. Cras porta ultrices ligula', 'https://robohash.org/blanditiisvoluptatemquia.png?size=50x50&set=set1', 42.8970535, '249 Autumn Leaf Terrace', '15705', 'Galicia', 'Castilla - Leon', 'Alquiler', 18805.38, 0, 99, 2, true, true, true, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Charlie Chan''s Secret', 'vel luctus justo pretium ut. Phasellus convallis', 'https://robohash.org/aliquamquoseum.png?size=50x50&set=set1', 42.8045028, '20444 Hoard Crossing', '31005', 'Navarra', 'Andalucia', 'Venta', 13882.18, 4, 99, 2, true, false, true, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Story of Mankind, The', 'vitae commodo ipsum ligula vitae neque. Pellentesque in enim at risus malesuada faucibus non a augue. Cras porta ultrices ligula', 'https://robohash.org/autemisteanimi.png?size=50x50&set=set1', 42.5944931, '07 Meadow Valley Junction', '24010', 'Castilla - Leon', 'Andalucia', 'Obra nueva', 87175.71, 4, 83, 0, false, false, false, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Bloody Angels (1732 Høtten: Marerittet har et postnummer)', 'dolor nec auctor finibus', 'https://robohash.org/voluptasquinatus.png?size=50x50&set=set1', 42.4556093, '8338 Summer Ridge Drive', '36156', 'Galicia', 'Comunidad Valenciana', 'Obra nueva', 75329.45, 4, 120, 2, false, false, false, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Happy Feet Two', 'vitae commodo ipsum ligula vitae neque. Pellentesque in enim at risus malesuada faucibus non a augue. Cras porta ultrices ligula', 'https://robohash.org/sedcupiditatedicta.png?size=50x50&set=set1', 37.970285, '844 Cottonwood Drive', '30010', 'Murcia', 'Andalucia', 'Obra nueva', 2309.78, 3, 138, 3, true, true, true, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Abominable Dr. Phibes, The', 'nec fringilla tortor rutrum a. Proin imperdiet vitae mauris id molestie. Cras placerat nulla sed porta maximus. Nam fringilla porta massa', 'https://robohash.org/sintvoluptateeaque.png?size=50x50&set=set1', 42.2390986, '1988 Armistice Crossing', '36215', 'Galicia', 'Cataluna', 'Venta', 54550.75, 2, 87, 3, true, true, false, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Left Behind: The Movie', 'vel luctus justo pretium ut. Phasellus convallis', 'https://robohash.org/molestiaeipsaprovident.png?size=50x50&set=set1', 37.6118995, '24 Golf Hill', '30204', 'Murcia', 'Navarra', 'Obra nueva', 8553.13, 4, 146, 2, false, false, false, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Ferris Bueller''s Day Off', 'dolor nec auctor finibus', 'https://robohash.org/eummolestiaequisquam.png?size=50x50&set=set1', 42.8518656, '87 Kings Point', '15899', 'Galicia', 'Castilla - Leon', 'Obra nueva', 59893.42, 1, 95, 2, true, true, false, 2);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje, propietario_id) values ('Smurfs 2, The', 'vel luctus justo pretium ut. Phasellus convallis', 'https://robohash.org/remblanditiisqui.png?size=50x50&set=set1', 36.7226027, '214 Linden Lane', '29010', 'Andalucia', 'Andalucia', 'Venta', 78480.24, 4, 123, 0, false, true, false, 2);


